In [69]:
import numpy as np
import pandas as pd

In [70]:
df=pd.read_csv("inc_denoised_ecg_segments.csv")

In [71]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,171,172,173,174,175,176,177,178,179,target
0,-0.017178,-0.014565,-0.018054,-0.027078,-0.035279,-0.037698,-0.035369,-0.032681,-0.032234,-0.033392,...,-0.031731,-0.033445,-0.025976,-0.016459,-0.015748,-0.026377,-0.040318,-0.047678,-0.044880,1
1,-0.023714,-0.028039,-0.027732,-0.023316,-0.020723,-0.024598,-0.031731,-0.033445,-0.025976,-0.016459,...,-0.040545,-0.037275,-0.040280,-0.046313,-0.047484,-0.040555,-0.032600,-0.033649,-0.044206,1
2,-0.035985,-0.026312,-0.021737,-0.027196,-0.038348,-0.046210,-0.045916,-0.040545,-0.037275,-0.040280,...,0.006237,-0.000279,-0.007944,-0.012856,-0.009099,0.002670,0.014798,0.019607,0.015061,1
3,-0.025482,-0.026235,-0.030196,-0.033310,-0.034417,-0.036179,-0.039863,-0.041475,-0.036300,-0.027085,...,-0.021892,-0.018337,-0.010603,-0.000504,0.006521,0.005012,-0.005154,-0.017405,-0.024057,1
4,0.004409,-0.001297,-0.010207,-0.017905,-0.021665,-0.022605,-0.021892,-0.018337,-0.010603,-0.000504,...,-0.023203,-0.014232,-0.003828,0.001399,0.000910,-0.001072,-0.000728,0.001449,0.000692,1

In [72]:
# df.drop('Unnamed: 0',axis=1,inplace=True)

In [73]:
df

,0,1,2,3,4,5,6,7,8,9,...,171,172,173,174,175,176,177,178,179,target
0,-0.017178,-0.014565,-0.018054,-0.027078,-0.035279,-0.037698,-0.035369,-0.032681,-0.032234,-0.033392,...,-0.031731,-0.033445,-0.025976,-0.016459,-0.015748,-0.026377,-0.040318,-0.047678,-0.044880,1
1,-0.023714,-0.028039,-0.027732,-0.023316,-0.020723,-0.024598,-0.031731,-0.033445,-0.025976,-0.016459,...,-0.040545,-0.037275,-0.040280,-0.046313,-0.047484,-0.040555,-0.032600,-0.033649,-0.044206,1
2,-0.035985,-0.026312,-0.021737,-0.027196,-0.038348,-0.046210,-0.045916,-0.040545,-0.037275,-0.040280,...,0.006237,-0.000279,-0.007944,-0.012856,-0.009099,0.002670,0.014798,0.019607,0.015061,1
3,-0.025482,-0.026235,-0.030196,-0.033310,-0.034417,-0.036179,-0.039863,-0.041475,-0.036300,-0.027085,...,-0.021892,-0.018337,-0.010603,-0.000504,0.006521,0.005012,-0.005154,-0.017405,-0.024057,1
4,0.004409,-0.001297,-0.010207,-0.017905,-0.021665,-0.022605,-0.021892,-0.018337,-0.010603,-0.000504,...,-0.023203,-0.014232,-0.003828,0.001399,0.000910,-0.001072,-0.000728,0.001449,0.000692,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169635,0.000474,0.000856,0.002648,0.004572,0.005268,0.004473,0.003136,0.002391,0.002544,0.003135,...,0.179890,0.188410,0.194857,0.200494,0.206596,0.212933,0.218307,0.222271,0.225584,4
169636,-0.010354,-0.009146,-0.008420,-0.008949,-0.010532,-0.012083,-0.012571,-0.011794,-0.010452,-0.009665,...,-0.066075,-0.064658,-0.062317,-0.059546,-0.056219,-0.051647,-0.045585,-0.038886,-0.032853,1
169637,-0.017692,-0.018838,-0.019126,-0.018482,-0.017765,-0.017698,-0.017977,-0.017693,-0.016582,-0.015391,...,-0.051799,-0.047983,-0.042874,-0.037463,-0.032311,-0.027128,-0.021578,-0.016022,-0.011204,1
169638,-0.004375,-0.003663,-0.003858,-0.004625,-0.005082,-0.004760,-0.003914,-0.002976,-0.002122,-0.001456,...,-0.039680,-0.038604,-0.036034,-0.031812,-0.026737,-0.021678,-0.016671,-0.011196,-0.005316,1
169639,-0.012958,-0.012122,-0.010873,-0.009705,-0.008808,-0.008123,-0.007629,-0.007429,-0.007553,-0.007846,...,-0.054765,-0.054082,-0.052309,-0.048983,-0.044688,-0.040344,-0.036172,-0.031711,-0.026760,1

In [74]:
df['target'].value_counts()

1    152340
4     14994
3      2099
0       201
2         6
Name: target, dtype: int64

In [75]:
!pip install imblearn

Requirement already satisfied: imblearn in c:\users\sai teja\appdata\local\programs\python\python310\lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\users\sai teja\appdata\local\programs\python\python310\lib\site-packages (from imblearn) (0.12.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\sai teja\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn->imblearn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\sai teja\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn->imblearn) (1.10.0)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\sai teja\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn->imblearn) (1.2.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\sai teja\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn->imblearn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\sai teja\appdata\local\programs\python\python310\lib\site-packages (from imbalanced-learn->imblearn) (3.1.0)

[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [76]:
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

In [77]:
X = df.drop('target', axis=1)

In [78]:
y = df['target']

In [79]:
print("Original class distribution:")
print(y.value_counts())

Original class distribution:
1    152340
4     14994
3      2099
0       201
2         6
Name: target, dtype: int64

In [80]:
undersample_strategy = {1: 2000,4: 2000, 3: 2000}
undersample = RandomUnderSampler(sampling_strategy=undersample_strategy, random_state=42)

In [81]:
X_under, y_under = undersample.fit_resample(X, y)

In [82]:
minority_class_0 = df[df['target'] == 0]

In [83]:
df_combined = pd.concat([pd.DataFrame(X_under), pd.DataFrame(y_under)], axis=1)
df_combined = pd.concat([df_combined, minority_class_0], axis=0)

In [84]:
X_combined = df_combined.drop('target', axis=1)
y_combined = df_combined['target']

In [85]:
oversample_strategy = {0: 2000,2:2000}
oversample = RandomOverSampler(sampling_strategy=oversample_strategy, random_state=42)

In [86]:
X_resampled, y_resampled = oversample.fit_resample(X_combined, y_combined)

In [87]:
print("Resampled class distribution:")
print(y_resampled.value_counts())

Resampled class distribution:
0    2000
1    2000
2    2000
3    2000
4    2000
Name: target, dtype: int64

In [88]:
df_resampled = pd.concat([pd.DataFrame(X_resampled), pd.DataFrame(y_resampled, columns=['target'])], axis=1)

In [89]:
df_resampled.to_csv('resampled_dataset.csv', index=False)

In [90]:
df_resampled.head()

,0,1,2,3,4,5,6,7,8,9,...,171,172,173,174,175,176,177,178,179,target
0,0.001399,-0.009637,-0.014483,-0.008217,0.003079,0.009108,0.006485,0.001058,-0.000345,0.002199,...,0.016842,0.020552,0.027698,0.034403,0.034483,0.027981,0.021803,0.021277,0.023957,0
1,-0.003450,-0.000507,0.007082,0.008675,0.000749,-0.007706,-0.006197,0.004054,0.011627,0.008940,...,-0.015202,0.000804,0.012121,0.011672,0.005584,0.004995,0.012480,0.020793,0.023928,0
2,-0.009487,-0.009848,-0.003642,-0.001382,-0.004602,-0.003511,0.009169,0.027220,0.037831,0.036531,...,0.121585,0.132136,0.149422,0.175916,0.206855,0.226794,0.221882,0.198265,0.181316,0
3,-0.033187,-0.039688,-0.035787,-0.023284,-0.017343,-0.025122,-0.036150,-0.034832,-0.019275,-0.004171,...,0.033417,0.026292,0.019084,0.007791,-0.003452,-0.006242,0.001555,0.012435,0.017095,0
4,-0.042631,-0.055215,-0.044489,-0.011118,0.020328,0.021075,-0.011683,-0.049862,-0.063069,-0.046808,...,0.033473,0.053263,0.071243,0.069895,0.047216,0.019986,0.007720,0.013408,0.024234,0

In [91]:
df_resampled.shape

(10000, 181)

In [92]:
df_resampled['target'].value_counts()

0    2000
1    2000
2    2000
3    2000
4    2000
Name: target, dtype: int64

In [96]:
df=pd.read_csv('incart_resampled.csv')

In [97]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,171,172,173,174,175,176,177,178,179,target
0,0.001399,-0.009637,-0.014483,-0.008217,0.003079,0.009108,0.006485,0.001058,-0.000345,0.002199,...,0.016842,0.020552,0.027698,0.034403,0.034483,0.027981,0.021803,0.021277,0.023957,0
1,-0.003450,-0.000507,0.007082,0.008675,0.000749,-0.007706,-0.006197,0.004054,0.011627,0.008940,...,-0.015202,0.000804,0.012121,0.011672,0.005584,0.004995,0.012480,0.020793,0.023928,0
2,-0.009487,-0.009848,-0.003642,-0.001382,-0.004602,-0.003511,0.009169,0.027220,0.037831,0.036531,...,0.121585,0.132136,0.149422,0.175916,0.206855,0.226794,0.221882,0.198265,0.181316,0
3,-0.033187,-0.039688,-0.035787,-0.023284,-0.017343,-0.025122,-0.036150,-0.034832,-0.019275,-0.004171,...,0.033417,0.026292,0.019084,0.007791,-0.003452,-0.006242,0.001555,0.012435,0.017095,0
4,-0.042631,-0.055215,-0.044489,-0.011118,0.020328,0.021075,-0.011683,-0.049862,-0.063069,-0.046808,...,0.033473,0.053263,0.071243,0.069895,0.047216,0.019986,0.007720,0.013408,0.024234,0

In [98]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
176       0
177       0
178       0
179       0
target    0
Length: 181, dtype: int64

In [99]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,171,172,173,174,175,176,177,178,179,target
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,-0.115805,-0.114866,-0.116473,-0.118851,-0.121424,-0.125515,-0.132623,-0.142241,-0.150929,-0.154101,...,-0.380734,-0.393037,-0.398116,-0.400485,-0.400319,-0.394719,-0.383009,-0.369314,-0.358515,2.000000
std,0.405440,0.407203,0.416467,0.422540,0.433125,0.452654,0.475734,0.495474,0.504710,0.502354,...,2.350989,2.426796,2.452720,2.434818,2.392921,2.346026,2.299982,2.247541,2.181781,1.414284
min,-4.108663,-4.015041,-3.969519,-3.929074,-3.841896,-3.660625,-3.388398,-3.127488,-3.030436,-3.142548,...,-12.473574,-12.941374,-13.115615,-13.052477,-12.854630,-12.609053,-12.345850,-12.047969,-11.695578,0.000000
25%,-0.117668,-0.112574,-0.111582,-0.109501,-0.106131,-0.102335,-0.103589,-0.098971,-0.100280,-0.098431,...,-0.059452,-0.061764,-0.063036,-0.061264,-0.056874,-0.053401,-0.050035,-0.052330,-0.056350,1.000000
50%,-0.019209,-0.018196,-0.016574,-0.014762,-0.015356,-0.014250,-0.013982,-0.014034,-0.013554,-0.013064,...,0.013305,0.008869,0.005748,0.002601,-0.003452,-0.008027,-0.007193,-0.009237,-0.006603,2.000000
75%,0.048431,0.051778,0.051754,0.054997,0.056946,0.056022,0.044620,0.044368,0.048478,0.050063,...,0.091889,0.082248,0.073252,0.065924,0.058087,0.049325,0.042849,0.037379,0.037763,3.000000
max,3.000734,2.613794,2.638089,3.415893,3.690467,3.675315,3.802494,3.580194,3.241921,3.003617,...,5.325755,5.250826,5.249945,5.319290,5.386051,5.381684,5.308066,5.239584,5.264964,4.000000